name: Artifacts
version: '1.0'
main: me.imhermes.artifacts.Artifacts
api-version: '1.21'
author: ImHermes
database: false
description: Artifacts plugin, "commission coded" (you could say)
website: https://imhermes.me
commands:
  admin-artifacts:
    permission: artifacts.admin
    description: Admin command for artifacts
    usage: /admin-artifacts <remove <artifact ID> | add <player> <artifact ID> | reload | list [<player>] | set <artifact ID> [-noReturn -noRemove] | delete <artifact ID> >
  artifact:
    description: Command that shows your artifacts